services:
  - type: web
    name: pgz-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: ohio
    plan: starter
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        fromService:
          type: redis
          name: pgz-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: pgz-redis
          property: port
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false

  - type: redis
    name: pgz-redis
    region: ohio
    plan: free
    ipAllowList: []
